FROM node:22-alpine

WORKDIR /app

# Instala dependencias globales útiles
# RUN npm install -g npm@latest

# Copia solo package.json primero (mejor cache)
COPY package*.json ./
RUN npm install

# Copia el resto del proyecto
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]

